# Matrix Completion using SVD Matrix Factorization

Based on https://beckernick.github.io/matrix-factorization-recommender/

Data: 1 million movie ratings available from the MovieLens project. 
The MovieLens datasets were collected by GroupLens Research at the University of Minnesota.

# Preprocessing

In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.metrics import mean_squared_error

ratings_list = [i.strip().split("::") for i in open('netflix1m/ml-1m/ratings.dat', 'r').readlines()]
ratings_df = pd.DataFrame(ratings_list, columns = ['UserID', 'MovieID', 'Rating', 'Timestamp'], dtype = int)
ratings_df['Rating']=ratings_df['Rating'].apply(pd.to_numeric)

In [2]:
random.seed(123)

In [3]:
ratings_df.head()

  UserID MovieID  Rating  Timestamp
0      1    1193       5  978300760
1      1     661       3  978302109
2      1     914       3  978301968
3      1    3408       4  978300275
4      1    2355       5  978824291

In [4]:
print("#users: "+ str(ratings_df.UserID.nunique()))
print("#movies: "+ str(ratings_df.MovieID.nunique()))
print("#ratings %: "+ str(ratings_df.shape[0]/(ratings_df.UserID.nunique()*ratings_df.MovieID.nunique())*100))

#users: 6040
#movies: 3706
#ratings %: 4.468362562231285

In [5]:
ratings_df.Rating.describe()

count    1.000209e+06
mean     3.581564e+00
std      1.117102e+00
min      1.000000e+00
25%      3.000000e+00
50%      4.000000e+00
75%      4.000000e+00
max      5.000000e+00
Name: Rating, dtype: float64

pivot ratings_df to get user-rating matrix format

In [6]:
R_df = ratings_df.pivot(index = 'UserID', columns ='MovieID', values = 'Rating').fillna(0)
R_df.head()

MovieID,1,10,100,1000,1002,1003,1004,1005,1006,1007,...,99,990,991,992,993,994,996,997,998,999
UserID,,,,,,,,,,,,,,,,,,,,,
1,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1000,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1001,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

de-mean the data (normalize by each users mean) and convert it from a dataframe to a numpy array.

In [7]:
R = R_df.values
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

# Sample test data

create test data by sampling (and removing) 500 ratings

In [8]:
rated_indices = np.argwhere(R_demeaned>0)

In [9]:
test_set = random.sample(list(rated_indices),500)

In [10]:
print("1st index is "+str(test_set[0])+" and its rating is "+str(R_demeaned[test_set[0][0],test_set[0][1]]))

1st index is [ 296 3087] and its rating is 4.705342687533729

In [11]:
test_ratings = []
for i in range(len(test_set)):
    test_ratings.append(R_demeaned[test_set[i][0],test_set[i][1]])
    R_demeaned[test_set[i][0],test_set[i][1]]=0

In [12]:
print("1st index is "+str(test_set[0])+" and its rating is "+str(R_demeaned[test_set[0][0],test_set[0][1]]))

1st index is [ 296 3087] and its rating is 0.0

# Singular Value Decomposition

Scipy function svds allow to choose the number of latent factors

In [13]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 50)

convert it to the diagonal matrix form.

In [14]:
sigma = np.diag(sigma)

# Making Predictions from the Decomposed Matrices

can predict by simply multiplying the matrices to get the rank k=50 approximation of the ratings matrix.
(also need to add the user means back)

In [15]:
predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(predicted_ratings, columns = R_df.columns)

In [16]:
pred_set = [predicted_ratings[x[0],x[1]] for x in test_set]

In [17]:
res_df = pd.DataFrame()

res_df["act"]=test_ratings
res_df["pred"]=pred_set
res_df.head(10)

        act      pred
0  4.705343  2.286855
1  2.844307  1.652314
2  0.058824  0.738982
3  4.817323  1.178691
4  1.869401  0.226414
5  3.722612  2.737643
6  1.586346  1.856473
7  4.871560  1.768516
8  2.588505  2.578916
9  0.942256  0.349585

finally, let's evaluate the RMSE:

In [18]:
np.sqrt(mean_squared_error(test_ratings,pred_set))

2.3372644045868896

### Student solution - Solve matrix copletion using SVT

In [42]:
import datetime
STEP_INCREMENT = 5
EPSILON = 0.1
max_iteration = 150

In [43]:
def shrink(Y, sk, tau):
    sk = int(sk)
    while True:
        U, S, V = svds(Y, k=sk)
        if S[-1] <= tau:
#             print('stop because tau is bigger than S[-1](%s)' % S[-1])
            break
        sk = min(sk+ STEP_INCREMENT,Y.shape[0], Y.shape[1])
        if sk == min(Y.shape): 
#             print('stop beacouse sk == yshape %s' % sk)
            break
    new_r = np.argmax(S>tau)
    S = np.diag(S)
    X = np.dot(np.dot(U, S), V)
    return X, new_r

def compute_svt(actual_rating, test_ratings, mask):
    tau = 1 * np.sum(mask.shape) / 2 # 5 * np.sum(mask.shape) / 2
    delta_k = 0.1  #2 * np.prod(mask.shape) / np.sum(mask)
    Y = np.zeros_like(actual_rating)
    
    
    r=0
    start_time = datetime.datetime.now()
    for i in range(max_iteration):
        print ('iter number %s' % i)
        sk = r+1
        X, r =shrink(Y, sk, tau)
        Y+= delta_k * mask*(actual_rating - X) 
        
        recon_error = np.linalg.norm(mask * (X - actual_rating)) / np.linalg.norm(mask * actual_rating)

        pred_set = [X[x[0],x[1]] for x in test_set]
        print ('    ' + str((datetime.datetime.now() - start_time)) + ' seconds elapsed: rmse- %s, recon_error-%s' % (np.sqrt(mean_squared_error(test_ratings,pred_set)), recon_error))
        if recon_error< EPSILON:
            break
    
    return X

In [44]:
actual_rating = R.copy()
mask = np.ones(R_demeaned.shape)
for i in range(len(test_set)):
    mask[test_set[i][0],test_set[i][1]]=0
    

compute_svt(actual_rating, test_ratings, mask)

iter number 0
    0:00:01.207285 seconds elapsed: rmse- 3.4602495931970076, recon_error-1.0
iter number 1
    0:00:02.252234 seconds elapsed: rmse- 3.3812897114579448, recon_error-0.9755233504587356
iter number 2
    0:00:03.436558 seconds elapsed: rmse- 3.312493857112353, recon_error-0.9552366585398492
iter number 3
    0:00:04.691338 seconds elapsed: rmse- 3.252534502538164, recon_error-0.9384822373993462
iter number 4
    0:00:05.893657 seconds elapsed: rmse- 3.2002478443047115, recon_error-0.9246879955904516
iter number 5
    0:00:06.969464 seconds elapsed: rmse- 3.1546175876676816, recon_error-0.9133614196763781
iter number 6
    0:00:08.097733 seconds elapsed: rmse- 3.114759237512264, recon_error-0.9040824385741406
iter number 7
    0:00:09.188962 seconds elapsed: rmse- 3.0799051709785297, recon_error-0.8964957053791173
iter number 8
    0:00:10.349886 seconds elapsed: rmse- 3.049390699877347, recon_error-0.890302767493016
iter number 9
    0:00:11.512087 seconds elapsed: rmse- 3.0226412589582936, recon_error-0.8852544908508625
iter number 10
    0:00:12.613823 seconds elapsed: rmse- 2.999160788966605, recon_error-0.88114399043415
iter number 11
    0:00:13.674711 seconds elapsed: rmse- 2.9785213267956965, recon_error-0.8778002166653714
iter number 12
    0:00:14.782850 seconds elapsed: rmse- 2.9603537711213344, recon_error-0.8750822649241554
iter number 13
    0:00:15.856482 seconds elapsed: rmse- 2.9443397606208688, recon_error-0.8728744153106972
iter number 14
    0:00:16.941015 seconds elapsed: rmse- 2.9302045818266262, recon_error-0.8710818697994744
iter number 15
    0:00:18.014696 seconds elapsed: rmse- 2.9177110128175268, recon_error-0.8696271301947046
iter number 16
    0:00:19.081850 seconds elapsed: rmse- 2.9066540051757093, recon_error-0.8684469486289944
iter number 17
    0:00:20.161602 seconds elapsed: rmse- 2.896856107948727, recon_error-0.8674897789999664
iter number 18
    0:00:21.235773 seconds elapsed: rmse- 2.8881635420883396, recon_error-0.8667136597215165
iter number 19
    0:00:22.431702 seconds elapsed: rmse- 2.8804428406534663, recon_error-0.8660844632503338
iter number 20
    0:00:23.588194 seconds elapsed: rmse- 2.873577977964269, recon_error-0.8655744544778256
iter number 21
    0:00:24.696434 seconds elapsed: rmse- 2.867467919157347, recon_error-0.8651611072245343
iter number 22
    0:00:25.992780 seconds elapsed: rmse- 2.8620245297293616, recon_error-0.8648261351010397
iter number 23
    0:00:27.267629 seconds elapsed: rmse- 2.8571707923559613, recon_error-0.8645546995434497
iter number 24
    0:00:28.534529 seconds elapsed: rmse- 2.852839285349977, recon_error-0.8643347637131629
iter number 25
    0:00:29.765365 seconds elapsed: rmse- 2.848970883457259, recon_error-0.8641565661078887
iter number 26
    0:00:30.991063 seconds elapsed: rmse- 2.8455136466516753, recon_error-0.8640121921728487
iter number 27
    0:00:32.268211 seconds elapsed: rmse- 3.2283002290023015, recon_error-1.0297879744836402
iter number 28
    0:00:33.717902 seconds elapsed: rmse- 2.7972539239798038, recon_error-0.8636537748785252
iter number 29
    0:00:34.966861 seconds elapsed: rmse- 2.799033845708344, recon_error-0.8636048651172156
iter number 30
    0:00:36.268802 seconds elapsed: rmse- 2.8006423533186573, recon_error-0.8635652445477986
iter number 31
    0:00:37.580614 seconds elapsed: rmse- 2.8020949952730922, recon_error-0.8635331491584625
iter number 32
    0:00:38.866974 seconds elapsed: rmse- 3.2213224101155142, recon_error-1.0426800607631184
iter number 33
    0:00:40.116793 seconds elapsed: rmse- 2.7623134603751365, recon_error-0.865785949413692
iter number 34
    0:00:41.711413 seconds elapsed: rmse- 2.767268890480834, recon_error-0.8653325086837722
iter number 35
    0:00:42.991205 seconds elapsed: rmse- 2.771796010098974, recon_error-0.8649650306176215
iter number 36
    0:00:44.316013 seconds elapsed: rmse- 3.3781194146971676, recon_error-1.0654314568457246
iter number 37
    0:00:45.587060 seconds elapsed: rmse- 2.7380566582510903, recon_error-0.8688624262637085
iter number 38
    0:00:46.830263 seconds elapsed: rmse- 2.7449747849695187, recon_error-0.8678267121576754
iter number 39
    0:00:48.196344 seconds elapsed: rmse- 3.2143280431781793, recon_error-1.0689973139976983
iter number 40
    0:00:49.553672 seconds elapsed: rmse- 2.716679996792907, recon_error-0.8730197080139362
iter number 41
    0:00:50.886207 seconds elapsed: rmse- 2.7250645260664927, recon_error-0.8711997974523719
iter number 42
    0:00:52.231919 seconds elapsed: rmse- 2.732897929781179, recon_error-0.8697228107582315
iter number 43
    0:00:53.592451 seconds elapsed: rmse- 3.213734787402095, recon_error-1.0736942575129222
iter number 44
    0:00:54.863512 seconds elapsed: rmse- 2.7070837710430546, recon_error-0.8754358463226415
iter number 45
    0:00:56.105465 seconds elapsed: rmse- 2.716050040792139, recon_error-0.873161556027594
iter number 46
    0:00:57.706689 seconds elapsed: rmse- 3.396479041433955, recon_error-1.1058273385032935
iter number 47
    0:00:59.007705 seconds elapsed: rmse- 2.6937544305078385, recon_error-0.8795216777092073
iter number 48
    0:01:00.324273 seconds elapsed: rmse- 3.3608779820088737, recon_error-1.1207700853881877
iter number 49
    0:01:01.686988 seconds elapsed: rmse- 2.6761691235293967, recon_error-0.8865588883159522
iter number 50
    0:01:03.101580 seconds elapsed: rmse- 2.686387562835296, recon_error-0.8822056594142886
iter number 51
    0:01:04.447891 seconds elapsed: rmse- 3.215184234589299, recon_error-1.109182263012564
iter number 52
    0:01:05.921529 seconds elapsed: rmse- 2.6704314172668946, recon_error-0.8894089846670942
iter number 53
    0:01:07.745063 seconds elapsed: rmse- 2.680727590737722, recon_error-0.884526417703237
iter number 54
    0:01:09.212478 seconds elapsed: rmse- 3.4118610376109526, recon_error-1.1328520290996726
iter number 55
    0:01:10.501519 seconds elapsed: rmse- 2.665996927281449, recon_error-0.8918326608080852
iter number 56
    0:01:11.915168 seconds elapsed: rmse- 3.2168066009820593, recon_error-1.1187229128222547
iter number 57
    0:01:13.224137 seconds elapsed: rmse- 2.6545237660120065, recon_error-0.8992862105358486
iter number 58
    0:01:14.666044 seconds elapsed: rmse- 3.376211326769113, recon_error-1.1561163652109776
iter number 59
    0:01:16.035107 seconds elapsed: rmse- 2.645723035002021, recon_error-0.9066870789989401
iter number 60
    0:01:17.606491 seconds elapsed: rmse- 2.655477319151574, recon_error-0.8986239398906125
iter number 61
    0:01:19.074915 seconds elapsed: rmse- 3.423379114689653, recon_error-1.1511537277015218
iter number 62
    0:01:20.448144 seconds elapsed: rmse- 2.6464439174377974, recon_error-0.9060354566937806
iter number 63
    0:01:21.878258 seconds elapsed: rmse- 3.2238889871585963, recon_error-1.1454560819595423
iter number 64
    0:01:23.276885 seconds elapsed: rmse- 2.6395571699121962, recon_error-0.9132661921848498
iter number 65
    0:01:24.689090 seconds elapsed: rmse- 2.648737182793305, recon_error-0.9040045089093106
iter number 66
    0:01:26.164993 seconds elapsed: rmse- 3.518054280836748, recon_error-1.1943820158667589
iter number 67
    0:01:27.570885 seconds elapsed: rmse- 2.641296051393272, recon_error-0.9112959151219366
iter number 68
    0:01:28.989450 seconds elapsed: rmse- 3.3944168418701315, recon_error-1.1907370287631691
iter number 69
    0:01:30.378529 seconds elapsed: rmse- 2.6356336254410135, recon_error-0.9183306620871515
iter number 70
    0:01:31.774830 seconds elapsed: rmse- 3.2332963620441943, recon_error-1.1711315877274147
iter number 71
    0:01:33.145201 seconds elapsed: rmse- 2.631453459545259, recon_error-0.9250362517213103
iter number 72
    0:01:34.538207 seconds elapsed: rmse- 3.4592171145130672, recon_error-1.2021654681363023
iter number 73
    0:01:36.108362 seconds elapsed: rmse- 2.6284346177976405, recon_error-0.9313661995481297
iter number 74
    0:01:37.580275 seconds elapsed: rmse- 3.5599807469828755, recon_error-1.2309548802162287
iter number 75
    0:01:38.954988 seconds elapsed: rmse- 2.626273140841768, recon_error-0.9372981493316805
iter number 76
    0:01:40.374201 seconds elapsed: rmse- 3.2397099574420385, recon_error-1.1853944334955557
iter number 77

    0:01:41.795717 seconds elapsed: rmse- 2.6248139173148073, recon_error-0.9428250942002167
iter number 78
    0:01:43.225956 seconds elapsed: rmse- 3.4141920899580502, recon_error-1.2239760895998388
iter number 79
    0:01:44.750622 seconds elapsed: rmse- 2.6238643502906362, recon_error-0.9479473512321979
iter number 80
    0:01:46.372399 seconds elapsed: rmse- 3.476473611972494, recon_error-1.2246643899995933
iter number 81
    0:01:47.790921 seconds elapsed: rmse- 2.623282118287658, recon_error-0.9526751944494095
iter number 82
    0:01:49.178061 seconds elapsed: rmse- 3.5832569974992188, recon_error-1.259723849563586
iter number 83
    0:01:50.569446 seconds elapsed: rmse- 2.623048121231187, recon_error-0.9570247963366713
iter number 84
    0:01:51.948492 seconds elapsed: rmse- 3.2571937112083873, recon_error-1.2193516776186872
iter number 85
    0:01:53.339565 seconds elapsed: rmse- 2.623041140217467, recon_error-0.9610166799236972
iter number 86
    0:01:54.730651 seconds elapsed: rmse- 3.4969247401237182, recon_error-1.2809286365477996
iter number 87
    0:01:56.116423 seconds elapsed: rmse- 2.6231392936608966, recon_error-0.9646680399923266
iter number 88
    0:01:57.692789 seconds elapsed: rmse- 3.6079583121634506, recon_error-1.2766446155311806
iter number 89
    0:01:59.144029 seconds elapsed: rmse- 2.6234698768929077, recon_error-0.9680028529401026
iter number 90
    0:02:00.555694 seconds elapsed: rmse- 3.508989697463378, recon_error-1.2644841185592641
iter number 91
    0:02:02.150944 seconds elapsed: rmse- 3.4532479971838845, recon_error-1.2813106974632102
iter number 92
    0:02:03.601768 seconds elapsed: rmse- 2.629561329928784, recon_error-0.9951397593091168
iter number 93
    0:02:05.013312 seconds elapsed: rmse- 3.283684949345624, recon_error-1.26264774480284
iter number 94
    0:02:06.411835 seconds elapsed: rmse- 2.6297858858714975, recon_error-0.9956251419089989
iter number 95
    0:02:07.927051 seconds elapsed: rmse- 3.6271725828121704, recon_error-1.3005618848364746
iter number 96
    0:02:09.302662 seconds elapsed: rmse- 2.6300089794549595, recon_error-0.9960606497810812
iter number 97
    0:02:10.851222 seconds elapsed: rmse- 3.516018953490536, recon_error-1.2726559228139718
iter number 98
    0:02:12.235701 seconds elapsed: rmse- 2.6301430710268017, recon_error-0.9964531545846352
iter number 99
    0:02:13.758745 seconds elapsed: rmse- 3.2882523943808355, recon_error-1.2691404085236202
iter number 100
    0:02:15.425404 seconds elapsed: rmse- 2.6303313818928196, recon_error-0.9968088775738811
iter number 101
    0:02:16.994052 seconds elapsed: rmse- 3.473357984434303, recon_error-1.3089938008483109
iter number 102
    0:02:18.539731 seconds elapsed: rmse- 2.6306893533776217, recon_error-0.9971283693914581
iter number 103
    0:02:20.193509 seconds elapsed: rmse- 3.537396852981888, recon_error-1.338996367950799
iter number 104
    0:02:22.004157 seconds elapsed: rmse- 3.673303813661583, recon_error-1.3351176100244024
iter number 105
    0:02:23.423936 seconds elapsed: rmse- 2.642762285541389, recon_error-1.0236025694804778
iter number 106
    0:02:24.985415 seconds elapsed: rmse- 3.3005371874255345, recon_error-1.2864773564402094
iter number 107
    0:02:26.608332 seconds elapsed: rmse- 2.641431433924138, recon_error-1.021179997636547
iter number 108
    0:02:28.102108 seconds elapsed: rmse- 3.5577656143243703, recon_error-1.3198765838779092
iter number 109
    0:02:29.625034 seconds elapsed: rmse- 2.6403142623710294, recon_error-1.0190096825300134
iter number 110
    0:02:31.413452 seconds elapsed: rmse- 3.68872444112566, recon_error-1.3549478790860046
iter number 111
    0:02:33.089628 seconds elapsed: rmse- 2.6393144993999216, recon_error-1.0170663513108835
iter number 112
    0:02:34.917169 seconds elapsed: rmse- 3.500671053546775, recon_error-1.3438920655175908
iter number 113
    0:02:36.642562 seconds elapsed: rmse- 3.539784135218768, recon_error-1.3773405043258269
iter number 114
    0:02:39.226349 seconds elapsed: rmse- 2.6539868305574803, recon_error-1.042752813526497
iter number 115
    0:02:40.975049 seconds elapsed: rmse- 3.3303910122611744, recon_error-1.326085160210515
iter number 116
    0:02:42.588815 seconds elapsed: rmse- 2.6514607002480446, recon_error-1.0382818320096077
iter number 117
    0:02:44.330502 seconds elapsed: rmse- 3.5796341672184258, recon_error-1.3433804856545475
iter number 118
    0:02:46.022197 seconds elapsed: rmse- 2.649373019078244, recon_error-1.034292557584597
iter number 119
    0:02:47.737904 seconds elapsed: rmse- 3.7289844738574573, recon_error-1.3827237819997056
iter number 120
    0:02:49.554316 seconds elapsed: rmse- 3.579332021953144, recon_error-1.3940799534971733
iter number 121
    0:02:51.202270 seconds elapsed: rmse- 2.666766266198588, recon_error-1.0591282269320443
iter number 122
    0:02:53.055734 seconds elapsed: rmse- 3.7692671522370946, recon_error-1.4122232455597026
iter number 123
    0:02:54.875230 seconds elapsed: rmse- 2.6618277407956352, recon_error-1.052859086357595
iter number 124
    0:02:56.826248 seconds elapsed: rmse- 3.3614854590663903, recon_error-1.3630270874692676
iter number 125
    0:02:59.085429 seconds elapsed: rmse- 3.5438135254168395, recon_error-1.3955657889333906
iter number 126
    0:03:00.764358 seconds elapsed: rmse- 2.680251804838829, recon_error-1.0766406568577385
iter number 127
    0:03:02.332605 seconds elapsed: rmse- 3.7699020117423503, recon_error-1.423069884125664
iter number 128
    0:03:03.929426 seconds elapsed: rmse- 2.6735495303995056, recon_error-1.0684169598611746
iter number 129
    0:03:05.772783 seconds elapsed: rmse- 3.6316441697214428, recon_error-1.3970564143476576
iter number 130
    0:03:07.703569 seconds elapsed: rmse- 2.667638479282176, recon_error-1.061115769872315
iter number 131
    0:03:09.379886 seconds elapsed: rmse- 3.368711260900146, recon_error-1.372066376980018
iter number 132
    0:03:11.290334 seconds elapsed: rmse- 3.763555013126334, recon_error-1.4109170882639734
iter number 133
    0:03:13.530774 seconds elapsed: rmse- 2.686845916631506, recon_error-1.0843847777196298
iter number 134
    0:03:15.637040 seconds elapsed: rmse- 3.5757404954171412, recon_error-1.4407266661515115
iter number 135
    0:03:17.779101 seconds elapsed: rmse- 3.5612740353251437, recon_error-1.4139635665072279
iter number 136
    0:03:19.844599 seconds elapsed: rmse- 2.7068174779351706, recon_error-1.1060962732579156
iter number 137
    0:03:22.137521 seconds elapsed: rmse- 3.6214433685100578, recon_error-1.4456822036082702
iter number 138
    0:03:23.889020 seconds elapsed: rmse- 2.696889841753633, recon_error-1.09451918846855
iter number 139
    0:03:25.858122 seconds elapsed: rmse- 3.6597978193501395, recon_error-1.4249846896537304
iter number 140
    0:03:27.760013 seconds elapsed: rmse- 3.399515075605804, recon_error-1.405577036813746
iter number 141
    0:03:29.389115 seconds elapsed: rmse- 2.7128369914151422, recon_error-1.1155396485728737
iter number 142
    0:03:30.941934 seconds elapsed: rmse- 3.8287607323457347, recon_error-1.4696150700813635
iter number 143
    0:03:32.681019 seconds elapsed: rmse- 3.619638763981988, recon_error-1.4982124265787071
iter number 144
    0:03:34.289629 seconds elapsed: rmse- 2.7191951419669445, recon_error-1.1356192810884609
iter number 145
    0:03:36.108104 seconds elapsed: rmse- 3.847428225730395, recon_error-1.4822436580732115
iter number 146
    0:03:37.823363 seconds elapsed: rmse- 2.7168948619230253, recon_error-1.1199349531686233
iter number 147
    0:03:39.766132 seconds elapsed: rmse- 3.5933116950115442, recon_error-1.4507716036783898
iter number 148
    0:03:41.591019 seconds elapsed: rmse- 3.416248554606125, recon_error-1.4234313176689166
iter number 149
    0:03:43.137006 seconds elapsed: rmse- 2.741412663796596, recon_error-1.1389675374604638

array([[1.55454608, 0.71519208, 0.12043152, ..., 0.0316566 , 0.07325932,
        0.24408168],
       [8.60973239, 3.96103567, 0.66700057, ..., 0.17532763, 0.40574101,
        1.35182736],
       [1.89183816, 0.87036833, 0.14656171, ..., 0.03852518, 0.08915449,
        0.29704043],
       ...,
       [1.11637024, 0.51360276, 0.0864858 , ..., 0.02273364, 0.0526099 ,
        0.17528301],
       [2.44121228, 1.12311608, 0.18912202, ..., 0.04971257, 0.11504422,
        0.38329851],
       [6.20307116, 2.85381531, 0.48055524, ..., 0.12631865, 0.29232504,
        0.97395377]])